# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  encoding: utf8
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: gl_lti_production

development_lms:
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: canvas_production
  timeout: 5000

staging:
  <<: *default
  encoding: unicode
  database: gl_lti_production
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: 5432
  timeout: 5000
  pool: 20

staging_lms:
  <<: *default
  encoding: unicode
  database: canvas_production
  host: <%= ENV['LMS_DB_HOST'] %>
  username: <%= ENV['LMS_DB_USER'] %>
  password: <%= ENV['LMS_DB_PASSWORD'] %>
  port: 5432
  timeout: 5000
  pool: 20

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
# This pool size is same for delayed jobs so in future update accordingly
production:
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['DB_HOST'] %>
  database: gl_lti_production
  timeout: 5000
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  pool: 60

production_lms:
  adapter: postgresql
  encoding: utf8
  host: <%= ENV['LMS_DB_HOST'] %>
  database: canvas_production
  username: <%= ENV['LMS_DB_USER'] %>
  password: <%= ENV['LMS_DB_PASSWORD'] %>
  timeout: 5000
  pool: 60
